### ISSUE TITLE
Many multiple select2 in one page in nav-bar/div-content class jQuery

### ISSUE THREAD

**Issue by ArmandArthur** [Currency-One/select2-v4#1]
Hello,

I have tree multiselect on the one page. 
For every multiselect, i need to set multiples values into the select.

I tried <option selected="selected", it's works for one but the others, no working...

Could you help me please?

Thanks, have a good day

**Comment by daymosik** [comment]
Hi, this is our custom version of select2, which You shouldn't use because we don't provide support for it. You should use https://github.com/select2/select2 instead.

**Comment by ArmandArthur** [comment]
Thanks.
